language: node_js
node_js:
  - "6"
script: npm run build
addons:
  apt:
    packages:
    - pandoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
